[package]
name = "windows-side-dock"
version = "0.1.23"
edition = "2021"

[dependencies]
eframe = "0.33"
tray-icon = "0.25"
windows-sys = { version = "0.61", features = [
	"Win32_Foundation",
	"Win32_Graphics_Dwm",
	"Win32_Graphics_Gdi",
	"Win32_Storage_FileSystem",
	"Win32_System_Threading",
	"Win32_System_Registry",
	"Win32_System_SystemInformation",
	"Win32_UI_Accessibility",
	"Win32_UI_Shell",
	"Win32_UI_Controls_Dialogs",
	"Win32_UI_WindowsAndMessaging",
] }

[dev-dependencies]
egui_kittest = { version = "0.33", features = ["eframe"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(coverage_nightly)"] }

[build-dependencies]
embed-resource = "3.0.11"
